description: >
  Sets up caching, cargo authentication etc.
parameters:
  target:
    type: string
    description: cargo target to build
    default: x86_64-unknown-linux-gnu
  archive-prefix:
    type: string
    description: the archive name of the archive file that contains the test binaries
    default: cargo-tests-

steps:
  - with-rust:
      steps:
        - run: cargo nextest archive --target << parameters.target >> --archive-file=<< parameters.archive-prefix >><< parameters.target >>.tar.zst
  - persist_to_workspace:
      root: .
      paths:
        - << parameters.archive-prefix >><< parameters.target >>.tar.zst
