description: >
  Target independent docker images
docker:
  - image: ghcr.io/pascalkuthe/ferris_ci_<< parameters.image >>:latest
resource_class: << parameters.resource_class >>

parameters:
  resource_class:
    default: small
    type: string
  image:
    type: string
