description: >
  Default Linux Container for standard jobs
docker:
  - image: ghcr.io/pascalkuthe/ferris_ci_<< parameters.target >>:latest
    auth:
      username: $GITHUB_USERNAME
      password: $GITHUB_TOKEN
resource_class: << parameters.resource_class >>

parameters:
  resource_class:
    default: large
    type: string
  target:
    default: x86_64-unknown-linux-gnu
    type: string
